### ISSUE TITLE
This error

### ISSUE THREAD

**Issue by CRAG666** [FlyingHairball/mpv-osc-modern-extended#1]
[file] Cannot open file '/home/think-crag/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl': No such file or directory
Failed to open /home/think-crag/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl.
[vo/gpu] Interpolation now requires enabling display-sync mode.
[vo/gpu] E.g.: --video-sync=display-resample
[input] No key binding found for key 'Ctrl+Alt+3'.
[input] No key binding found for key 'Ctrl+Alt+3'.
[input] No key binding found for key 'Ctrl+Alt+3'.
[input] No key binding found for key 'Ctrl+Alt+3'.
[input] No key binding found for key 'Ctrl+Alt+3'.
[input] No key binding found for key 'Ctrl+Alt+3'.
AO: [pipewire] 48000Hz stereo 2ch floatp
Using hardware decoding (nvdec-copy).
VO: [gpu] 1280x640 nv12
[file] Cannot open file '/home/think-crag/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl': No such file or directory
Failed to open /home/think-crag/.config/mpv/shaders/Anime4K_Clamp_Highlights.glsl;~~/shaders/Anime4K_Restore_CNN_VL.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_VL.glsl;~~/shaders/Anime4K_Restore_CNN_M.glsl;~~/shaders/Anime4K_AutoDownscalePre_x2.glsl;~~/shaders/Anime4K_AutoDownscalePre_x4.glsl;~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl.

**Comment by FlyingHairball** [comment]
hey, thank you for downloading my OSC!

it seem there is separate version for anime4k shaders for linux and mac, I'm sorry for this confusion!

I will update the readme and repo to fix this shortly.

1. to fix the issue please download the correct shaders files from the official [Anime4k](https://github.com/bloc97/Anime4K/blob/master/md/GLSL_Instructions_Linux.md) github here.

2. remove the old shaders file in the mpv config directory and replace it with the newly downloaded one.

3. open ```input.conf``` from mpv config directory and remove the lines at the very end starting with ```Optimized shaders for lower-end GPU:``` and all below them, and replace them with the text from the ```input.conf from the download```.

4. open ```mpv.conf``` from mpv config directory and remove the first 5 lines, and replace them with the text from ```mpv.conf from the download```.

again, sorry for the confusion, let me know if you this solves the issue or if you find anything else.
